## Valores de configuração que serão usados pelo Helm para criar os manifests do Kubernetes.
image:
  repository: docker.io/brunovital12/my-fastapi-app
  tag: latest

  type: NodePort  # Define o tipo de serviço como NodePort
  port: 8000      # Porta interna do container
  nodePort: 31002 # Porta externa do cluster (opcional, se você quiser uma porta específica)

