
image:
  repository: docker.io/brunovital12/my-fastapi-app
  tag: latest

replicaCount: 2

service:
  type: NodePort  # Mudei para NodePort
  port: 8000
  nodePort: 30085  # Você pode definir um NodePort específico, ou deixar que o Kubernetes escolha um.

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: 6539-191-34-125-222.ngrok-free.app
      paths:
        - /