image:
  repository: docker.io/brunovital12/my-fastapi-app
  tag: latest
  type: NodePort
  port: 8000
  nodePort: 31002

provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
storage:
  type: memory
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false

  allInOne:
   extraEnv:
    - name: QUERY_BASE_PATH
      value: /jaeger
   resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 128Mi
   extraSecretMounts:
    - name: jaeger-tls
      mountPath: /tls
      subPath: ""
      secretName: jaeger-tls
      readOnly: true