image:
  repository: docker.io/brunovital12/my-fastapi-app
  tag: latest
  type: NodePort
  port: 8000
  nodePort: 31002

jaeger:
  collector:
    enabled: true
    replicaCount: 1

  agent:
    enabled: true
    replicaCount: 1

  query:
    enabled: true
    replicaCount: 1

  storage:
    type: memory  # Configure o armazenamento para memória
    # Remova a configuração de Cassandra para evitar conflitos
    cassandra:
      enabled: false

  service:
    type: ClusterIP
    port: 14250
    targetPort: 14250

  agentService:
    type: ClusterIP
    port: 5775

  resources:
    limits:
      memory: "4Gi"
      cpu: "2"
    requests:
      memory: "4Gi"
      cpu: "2"
