apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: meu-servicemonitor
  labels:
    release: prometheus
    app: meu-app
  namespace: observability
spec:
  selector:
    matchLabels:
      app: meu-app
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s
  namespaceSelector:
    any: true  # Monitorar todos os namespaces
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: meu-podmonitor
  labels:
    release: prometheus
    app: meu-app
  namespace: observability
spec:
  selector:
    matchLabels:
      app: meu-app
  podMetricsEndpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s
  namespaceSelector:
    any: true  # Monitorar todos os namespaces
