{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  endpoints:
    - port: {{ .Values.serviceMonitor.metricsPort }}
      path: {{ .Values.serviceMonitor.metricsPath }}
      interval: {{ .Values.serviceMonitor.scrapeInterval }}
  namespaceSelector:
    {{- if .Values.serviceMonitor.monitorAllNamespaces }}
    any: true
    {{- else }}
    matchNames:
      - {{ .Values.monitoring.namespace }}
    {{- end }}
{{- end }}

{{- if .Values.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-podmonitor
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  podMetricsEndpoints:
    - port: {{ .Values.podMonitor.metricsPort }}
      path: {{ .Values.podMonitor.metricsPath }}
      interval: {{ .Values.podMonitor.scrapeInterval }}
  namespaceSelector:
    {{- if .Values.podMonitor.monitorAllNamespaces }}
    any: true
    {{- else }}
    matchNames:
      - {{ .Values.monitoring.namespace }}
    {{- end }}
{{- end }}
