apiVersion: v1
kind: Service
metadata:
  name: my-fast-api
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}